# ==========================
# ⚙️ Server Settings
# ==========================
server.port=9090

# ⚙️ Database Settings
# ==========================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=phone_store;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=none          
spring.jpa.show-sql=true                    
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

logging.level.com.fonestore.user_api=DEBUG
logging.level.com.fonestore.user_api.config=DEBUG
logging.level.com.fonestore=DEBUG


management.endpoints.web.exposure.include=mappings
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework.http.converter.json=TRACE

app.jwt.secret=12345678901234567890123456789012
app.jwt.expiration-seconds=86400



# ==========================
# ⚙️ HikariCP Tuning (Fix lỗi Connection Closed)
# ==========================

# 1. Giảm thời gian sống tối đa của một connection.
# Khuyến nghị: Đặt thấp hơn timeout của DB (thường là 10-15 phút).
# Ở đây ta set là 10 phút (600000ms).
spring.datasource.hikari.max-lifetime=600000

# 2. Thời gian HikariCP sẽ "ping" database để giữ kết nối sống (Keepalive).
# Giúp ngăn chặn firewall đóng kết nối nhàn rỗi. Set nhỏ hơn max-lifetime.
# Ở đây set là 5 phút (300000ms).
spring.datasource.hikari.keepalive-time=300000

# 3. Thời gian chờ tối đa để lấy được 1 connection từ pool (30s là chuẩn).
spring.datasource.hikari.connection-timeout=30000

# 4. Số lượng connection tối đa (Tùy chỉnh theo cấu hình máy, mặc định là 10).
spring.datasource.hikari.maximum-pool-size=10